#Poorest Visuals configuration
#Sat Sep 12 13:53:01 MSK 2026
bind.China\ Hat=79
bind.Fullbright=71
bind.Zoom=67
module.Ambience.enabled=true
module.Ambience.setting.Blue=0.24
module.Ambience.setting.Green=0.11
module.Ambience.setting.Red=0.19
module.Armor\ HUD.enabled=true
module.Arraylist.enabled=false
module.Arraylist.setting.Gradient=true
module.Biome.enabled=false
module.Block\ Highlight.enabled=true
module.Block\ Highlight.setting.Color=Purple
module.Block\ Highlight.setting.Thickness=1.0
module.CPS.enabled=false
module.China\ Hat.enabled=false
module.China\ Hat.setting.Color=Green
module.China\ Hat.setting.Height=0.08
module.China\ Hat.setting.Opacity=0.7000000000000001
module.China\ Hat.setting.Outline=true
module.China\ Hat.setting.Radius=0.2
module.Clean\ Crosshair.enabled=true
module.Clean\ Crosshair.setting.Gap=3.0
module.Clean\ Crosshair.setting.Size=5.0
module.Clear\ Weather.enabled=true
module.Clock.enabled=true
module.Coordinates.enabled=true
module.Crosshair+.enabled=true
module.Crosshair+.setting.Gap=3.0
module.Crosshair+.setting.Length=5.0
module.Crosshair+.setting.Thickness=2.0
module.Crosshair.enabled=true
module.Custom\ Animations.enabled=true
module.Custom\ Animations.setting.Block\ Position\ X=0.0
module.Custom\ Animations.setting.Block\ Position\ Y=0.0
module.Custom\ Animations.setting.Block\ Position\ Z=0.0
module.Custom\ Animations.setting.Item\ Size\ X=1.6
module.Custom\ Animations.setting.Item\ Size\ Y=1.0
module.Custom\ Animations.setting.Item\ Size\ Z=1.0
module.Custom\ Animations.setting.Items\ Only=false
module.Custom\ Animations.setting.Position\ X=0.06
module.Custom\ Animations.setting.Position\ Y=0.0
module.Custom\ Animations.setting.Position\ Z=0.0
module.Custom\ Animations.setting.Preset=Swank
module.Custom\ Animations.setting.Swing\ Speed=1.0
module.Custom\ Animations.setting.Swing\ Strength=1.0
module.Direction.enabled=false
module.Entity\ Shadows.enabled=false
module.Entity\ Shadows.setting.Shadows=true
module.FOV.enabled=true
module.FOV.setting.FOV=114.0
module.FPS.enabled=true
module.FPS.setting.Scale=2.0
module.FPS.setting.Show\ Label=true
module.Fullbright.enabled=true
module.Hit\ Color.enabled=false
module.Hit\ Color.setting.Duration=5.0
module.Hit\ Color.setting.Intensity=0.55
module.Hit\ Particles.enabled=false
module.Hit\ Particles.setting.Amount=10.0
module.Hit\ Particles.setting.Spread=0.75
module.Hit\ Sound.enabled=true
module.Hit\ Sound.setting.Mute\ Vanilla\ Crit=true
module.Hit\ Sound.setting.Pitch=1.4500000000000002
module.Hit\ Sound.setting.Sound=bell
module.Hit\ Sound.setting.Trigger=Critical
module.Hit\ Sound.setting.Volume=1.4500000000000002
module.Hitboxes.enabled=true
module.Hitboxes.setting.Color=Purple
module.Hitboxes.setting.Range=96.0
module.Hitboxes.setting.Thickness=1.0
module.Hurt\ Cam.enabled=false
module.Hurt\ Cam.setting.Strength=1.0
module.InvMove.enabled=true
module.Item\ Physics.enabled=true
module.Item\ Physics.setting.Bounce=1.4500000000000002
module.Item\ Physics.setting.Flat\ On\ Ground=true
module.Item\ Physics.setting.Tumble=1.9500000000000002
module.Jump\ Circles.enabled=true
module.Jump\ Circles.setting.Color=Purple
module.Jump\ Circles.setting.Duration=2000.0
module.Jump\ Circles.setting.Line\ Width=1.0
module.Jump\ Circles.setting.Radius=2.9000000000000004
module.Keystrokes.enabled=true
module.No\ Block\ Overlay.enabled=false
module.No\ Boss\ Bar.enabled=false
module.No\ Debuffs.enabled=true
module.No\ Debuffs.setting.Blindness=true
module.No\ Debuffs.setting.Darkness=true
module.No\ Debuffs.setting.Nausea=true
module.No\ Fire\ Overlay.enabled=true
module.No\ Fog.enabled=false
module.No\ Player\ List.enabled=false
module.No\ Portal\ Overlay.enabled=true
module.No\ Powder\ Snow\ Overlay.enabled=false
module.No\ Pumpkin\ Overlay.enabled=true
module.No\ Scoreboard.enabled=false
module.No\ Spyglass\ Overlay.enabled=true
module.No\ Vignette.enabled=true
module.Performance.enabled=true
module.Performance.setting.Preset=Max FPS
module.Performance.setting.Render\ Distance=8.0
module.Performance.setting.Simulation\ Distance=5.0
module.Ping.enabled=true
module.Potion\ HUD.enabled=true
module.Target\ HUD.enabled=true
module.Target\ HUD.setting.Animation\ Speed=0.22
module.Target\ HUD.setting.Hold\ Time=2.5
module.Time\ Changer.enabled=true
module.Time\ Changer.setting.Time=16500.0
module.Trail\ Effects.enabled=true
module.Trail\ Effects.setting.Color=Purple
module.Trail\ Effects.setting.Duration=675.0
module.Trail\ Effects.setting.Length=68.0
module.Trail\ Effects.setting.Line\ Width=1.0
module.Watermark.enabled=true
module.Zoom.enabled=true
module.Zoom.setting.Smooth=false
module.Zoom.setting.Zoom\ FOV=58.0
